name: Xpose
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  # iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0     # Linting rules
  flutter_launcher_icons: ^0.13.1  # Icon generator plugin

flutter_icons:
  android: true                     # Generate Android launcher icon
  ios: true                         # Generate iOS launcher icon
  image_path: "assets/logo/xpose-logo.png"  # Path to your logo image (no double ".png")

flutter:
  uses-material-design: true

  assets:
    - assets/logo/xpose-logo.png
    - assets/logo/xpose-logo-round.png


