name: Xpose
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  image_picker: ^1.1.0
  http_parser: ^4.0.2
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  url_launcher: ^6.2.5
  file_picker: ^8.0.7
  geolocator: ^12.0.0
  flutter_recaptcha_v2_compat: ^1.0.5
  webview_flutter: ^4.4.0
  webview_flutter_android: ^4.8.2
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0     # Linting rules
  flutter_launcher_icons: ^0.13.1  # Icon generator plugin

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/xpose-logo-full.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/xpose-logo-full.png"


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo/xpose-logo.png
    - assets/logo/xpose-logo-round.png
    - assets/profile-fallback/profile-fallback.png



